### ISSUE TITLE
Unabble to `go get`

### ISSUE THREAD

**Issue by lfaoro** [securego/gosec#298]
### Summary 
Following the readme.md instructions `go get github.com/securego/gosec/cmd/gosec/...` is unable to install the program.

### Steps to reproduce the behavior
```bash
$ go get github.com/securego/gosec/cmd/gosec/...
go: finding github.com/securego/gosec/cmd/gosec/... latest
go: finding github.com/securego/gosec/cmd/gosec latest
go: finding github.com/securego/gosec/cmd latest
go: finding github.com/securego/gosec latest
go: downloading github.com/securego/gosec v0.0.0-20190320213014-eaba99df3732
go: extracting github.com/securego/gosec v0.0.0-20190320213014-eaba99df3732
go get github.com/securego/gosec/cmd/gosec/...: no matching versions for query "latest"
```

### gosec version
latest?

### Go version (output of 'go version')
go version go1.12.4 darwin/amd64

### Operating system / Environment
`macOS 10.14.4 (18E226)`

### Expected behavior
being able to run `gosec`

### Actual behavior
unable to run `gosec`

**Comment by MVrachev** [comment]
I had the same problem one or two days ago.

**Comment by gcmurphy** [comment]
Do you have GO111MODULE set if so what to?

**Comment by lfaoro** [comment]
```
$ env |grep GO11
GO111MODULE=on
```

**Comment by ccojocar** [comment]
@lfaoro It seems that running only `go get github.com/securego/gosec/cmd/gosec` works. 

There seems to be an issue related to this in Go modules https://github.com/golang/go/issues/27215

Can we close this issue? Thanks

**Comment by ccojocar** [comment]
I am closing this because it is possible to install gosec with `go get github.com/securego/gosec/cmd/gosec`. Feel free to open another issue if you still encounter the problem. Thanks

**Comment by ccojocar** [comment]
I updated the README in #308.

**Comment by eschwartz** [comment]
I'm still seeing this:

```
$ go get -u github.com/securego/gosec/cmd/gosec
go: downloading github.com/securego/gosec v2.2.0+incompatible
verifying github.com/securego/gosec@v2.2.0+incompatible: github.com/securego/gosec@v2.2.0+incompatible: reading https://sum.golang.org/lookup/github.com/securego/gosec@v2.2.0+incompatible: 410 Gone
~/dev/dce-cli$ go get -u github.com/securego/gosec/cmd/gosec@v2.2.0
go: finding github.com v2.2.0
go: finding github.com/securego/gosec/cmd v2.2.0
go: finding github.com/securego/gosec/cmd/gosec v2.2.0
go: finding github.com/securego v2.2.0
go: finding github.com/securego/gosec v2.2.0
go: downloading github.com/securego/gosec v2.2.0+incompatible
verifying github.com/securego/gosec@v2.2.0+incompatible: github.com/securego/gosec@v2.2.0+incompatible: reading https://sum.golang.org/lookup/github.com/securego/gosec@v2.2.0+incompatible: 410 Gone
```

I was able to work around this by setting `GO111MODULE=off`

```
$ GO111MODULE=off go get -u github.com/securego/gosec/cmd/gosec
```
