### ISSUE TITLE
Failure when running in a directory without Go packages, but with subdirectories with Go packages

### ISSUE THREAD

**Issue by jsullivan3** [securego/gosec#304]
### Summary 

Since commit https://github.com/securego/gosec/commit/85d180848dbb8f86cba5d71bbbe06e1b40ce2705, following invocation in a directory that contains no Go packages but contains subdirectories with Go packages fails:

`gosec -vendor -exclude=G104 ./...`

with the following error:

`[gosec] 2019/04/26 11:02:42 strconv.Atoi: parsing " no Go files in /home/jsullivan3/path/to/my/project": invalid syntax`

### Steps to reproduce the behavior

```
$ go get -u github.com/securego/gosec/cmd/gosec
$ go install github.com/securego/gosec/cmd/gosec/...
$ gosec -vendor -exclude=G104 ./...
```

### gosec version

Build from commit `85d180848dbb8f86cba5d71bbbe06e1b40ce2705`.

### Go version (output of 'go version')

`go version go1.12.4 linux/amd64`

### Operating system / Environment

RHEL 7.6 x86_64

### Expected behavior

`gosec` analyzes all packages within subdirectories of the current directory, even if the current directory contains no Go packages.

### Actual behavior

`gosec` searches all subdirectories of the current directory, then complains that no Go packages are found in the current directory.

**Comment by ccojocar** [comment]
@jsullivan3 I am closing this since this issue seems to be fixed after refactoring. Please feel free to reopen it if it does not work as expected. Thanks!

**Comment by jeffdc** [comment]
This does not seem to be fixed as part of the latest refactoring.

`go get-u github.com/securego/gosec/cmd/gosec`

and then run `gosec` on a directory without a go file in the root and this failure will still happen.

`[gosec] 2019/04/29 15:59:17 strconv.Atoi: parsing " no Go files in /path/to/my/project": invalid syntax`

**Comment by sanmarco** [comment]
@ccojocar I'm getting the same error after updating to the latest master. I built a simple case that hopefully helps reproducing it:

Create a folder with this structure:

```
- gosec-issue-304
  |- cmd
     |- main.go
  |- tests
     | - my_test.go
```

main.go:
```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("main")
}
```

my_test.go:
```go
package tests

import (
	"testing"
)

func TestMy(t *testing.T) {
}
```

From the folder `gosec-issue-304` run `go ./...`
It should produce the error:
[gosec] 2019/04/29 13:28:10 strconv.Atoi: parsing " no Go files in /go/src/gosecissue": invalid syntax

**Comment by ccojocar** [comment]
@jsullivan3 Thanks for validating again this issue. I think now should be fixed. Note that by default `gosec` does not check the tests file, you need to enable them explicitly. When I run now `gosec` on your example this is the output:

```bash
$gosec ./...
[gosec] 2019/04/30 08:21:02 Including rules: default
[gosec] 2019/04/30 08:21:02 Excluding rules: default
[gosec] 2019/04/30 08:21:02 Import directory: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/cmd
[gosec] 2019/04/30 08:21:02 Checking package: main
[gosec] 2019/04/30 08:21:02 Checking file: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/cmd/main.go
[gosec] 2019/04/30 08:21:02 Import directory: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/tests
Results:


Summary:
   Files: 1
   Lines: 9
   Nosec: 0
  Issues: 0
```

```bassh
gosec -tests ./...
[gosec] 2019/04/30 08:21:10 Including rules: default
[gosec] 2019/04/30 08:21:10 Excluding rules: default
[gosec] 2019/04/30 08:21:10 Import directory: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/tests
[gosec] 2019/04/30 08:21:11 Checking package: tests
[gosec] 2019/04/30 08:21:11 Checking package: tests
[gosec] 2019/04/30 08:21:11 Checking file: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/tests/my_test.go
[gosec] 2019/04/30 08:21:11 Checking package: main
[gosec] 2019/04/30 08:21:11 Checking file: /Users/cosmin/Library/Caches/go-build/ac/ac0261363f3573643ba8f5046c9d27739abebe6b83adaf1a0154df7f8f3d5b18-d
[gosec] 2019/04/30 08:21:11 Import directory: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/cmd
[gosec] 2019/04/30 08:21:11 Checking package: main
[gosec] 2019/04/30 08:21:11 Checking file: /Users/cosmin/projects/gosecs/samples/gosec-issue-304/cmd/main.go
Results:


Summary:
   Files: 3
   Lines: 62
   Nosec: 0
  Issues: 0
```

**Comment by jsullivan3** [comment]
To give credit where credit is due - @jeffdc confirmed that the issue still exists with the refactored code, and @sanmarco reproduced it and provided a simplified example of the error - thank you for your hard work and assistance!

I've built the fix you provided and verified that it addresses the issue in the original repository where the error was discovered by my team.  Thank you for the quick turnaround!

**Comment by jsullivan3** [comment]
I may have spoken too soon - turns out a similar issue exists when I use the `-vendor` flag in my repo:

```
[gosec] 2019/04/30 06:55:17 loading pkg dir "vendor/github.com/hpcloud/tail/winfile": no buildable Go source files in vendor/github.com/hpcloud/tail/winfile
```

The file in question is conditionally build for only Windows:

```
$ head vendor/github.com/hpcloud/tail/winfile/winfile.go 
// +build windows

package winfile

import (
	"os"
	"syscall"
	"unsafe"
)

```

Does the verification for the top-level directory not recurse?  It would seem that this no-buildable-Go-files check does not recurse.  I've reproduced this variation of the issue using @sanmarco 's example by adding the file `pkg/conditional/nobuild.go` with the following contents:

```
// +build windows

package conditional

import (
	"fmt"
)

func myfunc() {
	fmt.Printf("Hey, I built!\n")
}
```

The output of `gosec ./...` _with_ the fix is as follows:

```
 ../gosec/gosec ./...
[gosec] 2019/04/30 07:02:33 Including rules: default
[gosec] 2019/04/30 07:02:33 Excluding rules: default
[gosec] 2019/04/30 07:02:33 Import directory: /home/jsullivan/Projects/gosec-issue-304/pkg/conditional
[gosec] 2019/04/30 07:02:33 loading pkg dir "pkg/conditional": no buildable Go source files in pkg/conditional
```

**Comment by ccojocar** [comment]
Thanks for finding this. I pushed a fix for it.
